{% set name = "odc-stac" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f43b0ca074e69fc60408555bf5c266c00f46af3c97f6ede91c6858ce02d31e4a
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - affine
    - odc-geo >=0.4.7
    - rasterio >=1.0.0,!=1.3.0,!=1.3.1
    - dask-core
    - numpy >=1.20.0
    - pandas
    - pystac >=1.0.0,<2
    - toolz
    - xarray

test:
  imports:
    - odc.stac
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/opendatacube/odc-stac/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Tooling for converting STAC metadata to ODC data model
  description: |
    Load STAC `pystac.Items` into `xarray.Dataset`.

  doc_url: https://odc-stac.readthedocs.io/
  dev_url: https://github.com/opendatacube/odc-stac/

extra:
  recipe-maintainers:
    - kirill888
    - gadomski
    - alexgleith
