{% set name = "odc-stac" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af8bb740751c406b0e5038a384d31f6f440269d9e672484b8039d42e7d616cd9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - affine
    - odc-geo >=0.3.0
    - rasterio >=1.0.0,!=1.3.0,!=1.3.1
    - dask-core
    - numpy >=1.20.0
    - pandas
    - pystac >=1.0.0,<2
    - toolz
    - xarray

test:
  imports:
    - odc.stac
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/opendatacube/odc-stac/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Tooling for converting STAC metadata to ODC data model
  description: |
    Load STAC `pystac.Items` into `xarray.Dataset`.

  doc_url: https://odc-stac.readthedocs.io/
  dev_url: https://github.com/opendatacube/odc-stac/

extra:
  recipe-maintainers:
    - kirill888
    - gadomski
    - alexgleith
